/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vendapdv;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import static vendapdv.formaPagamento.dinheiro;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author isabe
 */
public class JPrincipal extends javax.swing.JDialog {

    /**
     * Creates new form JPrincipal
     */
    public JPrincipal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Connection conectarAoBanco() throws SQLException {
    String url = "jdbc:mysql://localhost:3306/vendapdv";
    String usuario = "root";
    String senha = "123456";
    return DriverManager.getConnection(url, usuario, senha);
}
    
    public void inserirFormaDePagamento(String formaPagamento) {
    try (Connection conn = conectarAoBanco()) {
        String sql = "INSERT INTO formapagamento (tipo) VALUES (?)";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setString(1, formaPagamento);
            int rowsAffected = stmt.executeUpdate();
            if (rowsAffected > 0) {
                System.out.println("Forma de pagamento salva com sucesso: " + formaPagamento);
            } else {
                System.out.println("Erro ao salvar forma de pagamento.");
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuclientes = new javax.swing.JMenu();
        jMenuprodutos = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jmenuclientes.setText("Clientes");
        jmenuclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuclientesActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmenuclientes);

        jMenuprodutos.setText("Produtos");
        jMenuprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuprodutosActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuprodutos);
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 951, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuprodutosActionPerformed

           JProdutos jProdutos = new JProdutos(this, true); // Crie a instância da janela JProdutos
            jProdutos.setVisible(true); // Exiba a janela JProdutos // TODO add your handling code here:
    }//GEN-LAST:event_jMenuprodutosActionPerformed

    private void jmenuclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuclientesActionPerformed
        JCliente jCliente = new JCliente(this, true); // Crie a instância da janela JCliente
        jCliente.setVisible(true); // Exiba a janela JCliente
    }//GEN-LAST:event_jmenuclientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JPrincipal dialog = new JPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuprodutos;
    private javax.swing.JMenu jmenuclientes;
    // End of variables declaration//GEN-END:variables
}
